version: '3'
services:  
    db:    
      image: postgres    
      environment:      
        POSTGRES_USER: postgres      
        POSTGRES_PASSWORD: password      
        POSTGRES_DB: Devops    
      ports:      
        - "5433:5432"  
        
    api:    
      image: prueba    
      environment:      
        PORT: 3000      
        DB_USER: postgres      
        DB_HOST: db      
        DB_DATABASE: Devops      
        DB_PASSWORD: password      
        DB_PORT: 5432    
      ports:      
        - "3000:3000"    
      depends_on:      
        - db